import { useState, useRef, useEffect } from "react";

const PlantIcon = ({ size = 20 }) => (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M12 21 C12 21 12 13 12 10" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" />
        <path d="M12 15 C10 12.5 7 11.5 6 8.5 C8.5 7.5 11.5 9.5 12 13" fill="currentColor" opacity="0.9" />
        <path d="M12 12 C14 9.5 17 8.5 18 5.5 C15.5 5.5 12.5 7.5 12 11" fill="currentColor" opacity="0.9" />
        <path d="M12 10.5 C12 8.5 13.5 7 14.2 5.2" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />
        <circle cx="10.2" cy="21.6" r="0.6" fill="currentColor" opacity="0.45" />
        <circle cx="12" cy="22.1" r="0.6" fill="currentColor" opacity="0.45" />
        <circle cx="13.8" cy="21.6" r="0.6" fill="currentColor" opacity="0.45" />
    </svg>
);

const ATTACH_OPTIONS = [
    { label: "Adjuntar", icon: "-" },
    { label: "Agregar a planeta", icon: "-" },
    { label: "Plugins", icon: "-" },
];

export default function ChatInput({ onEnviar }) {
    const [texto, setTexto] = useState("");
    const [attachOpen, setAttachOpen] = useState(false);
    const inputRef = useRef(null);
    const attachRef = useRef(null);

    const hasText = texto.trim().length > 0;

    useEffect(() => {
        const handler = (e) => {
            if (attachRef.current && !attachRef.current.contains(e.target)) {
                setAttachOpen(false);
            }
        };
        document.addEventListener("mousedown", handler);
        return () => document.removeEventListener("mousedown", handler);
    }, []);

    const handleSubmit = (e) => {
        e.preventDefault();
        if (!hasText) return;
        onEnviar?.(texto.trim());
        setTexto("");
        inputRef.current?.focus();
    };

    return (
        <footer className="w-full px-0 pb-4 sm:pb-6">
            <form
                onSubmit={handleSubmit}
                className="relative flex items-center gap-2 sm:gap-3 bg-[#DBD9D2] rounded-full px-3 py-2 sm:px-4 sm:py-2.5 shadow-[0_4px_20px_rgba(0,0,0,0.18),inset_0_1px_0_rgba(255,255,255,0.5)] focus-within:shadow-[0_6px_24px_rgba(0,0,0,0.22),inset_0_1px_0_rgba(255,255,255,0.5)] transition-shadow duration-200"
            >
                {/* Attach trigger */}
                <div ref={attachRef} className="relative flex-shrink-0">
                    <label
                        htmlFor="msg"
                        onClick={(e) => {
                            e.preventDefault();
                            setAttachOpen((v) => !v);
                        }}
                        title="Opciones"
                        className={[
                            "flex items-center justify-center w-7 h-7 sm:w-8 sm:h-8",
                            "text-xl sm:text-2xl font-light leading-none",
                            "cursor-pointer select-none rounded-full",
                            "transition-all duration-200",
                            attachOpen
                                ? "text-[#927455] rotate-45"
                                : "text-[#000000] hover:text-[#927455] hover:rotate-45",
                        ].join(" ")}
                    >
                        +
                    </label>

                    {/* Popover generated by claude*/}
                    {attachOpen && (
                        <div
                            role="menu"
                            className="absolute bottom-full left-0 mb-3 bg-[#DBD9D2] rounded-2xl p-2 flex flex-col gap-1 min-w-[180px] shadow-[0_6px_22px_rgba(0,0,0,0.22),0_1px_5px_rgba(0,0,0,0.1)] z-10 origin-bottom-left animate-[wallPopIn_0.2s_cubic-bezier(.34,1.56,.64,1)_forwards]"
                        >
                            {ATTACH_OPTIONS.map((opt) => (
                                <button
                                    key={opt.label}
                                    type="button"
                                    role="menuitem"
                                    onClick={() => setAttachOpen(false)}
                                    className="flex items-center gap-3 px-3 py-2.5 rounded-xl border-none bg-transparent cursor-pointer font-semibold text-sm text-[#3c3830] hover:bg-[rgba(74,103,65,0.13)] transition-colors text-left w-full"
                                >
                                    <span className="text-base leading-none">{opt.icon}</span>
                                    {opt.label}
                                </button>
                            ))}
                        </div>
                    )}
                </div>

                <input
                    ref={inputRef}
                    type="text"
                    id="msg"
                    name="msg"
                    placeholder="Pregunta lo que necesites a WALL-UI"
                    required
                    aria-required="true"
                    value={texto}
                    onChange={(e) => setTexto(e.target.value)}
                    className="flex-1 min-w-0 bg-transparent border-none outline-none text-sm sm:text-base font-medium text-[#3c3830] placeholder-[#a89e8a] placeholder:font-normal"
                />

                {/* Plant send button generated by claude*/}
                <button
                    type="submit"
                    aria-label="Enviar mensaje"
                    className={[
                        "flex-shrink-0 flex items-center justify-center",
                        "w-8 h-8 sm:w-9 sm:h-9 rounded-full border-none",
                        "transition-all duration-300",
                        hasText
                            ? "bg-gradient-to-br from-[#76B82A] to-[#3d6b26] text-[#d4eeaf] opacity-100 cursor-pointer shadow-[0_3px_10px_rgba(60,100,35,0.5)] hover:scale-105 active:scale-95"
                            : "bg-[#cec9bf] text-[#d4eeaf] opacity-50 cursor-default pointer-events-none",
                    ].join(" ")}
                >
                    <PlantIcon size={18} />
                </button>
            </form>

            <style>{`
                @keyframes wallPopIn {
                    from { opacity: 0; transform: scale(0.75) translateY(8px); }
                    to   { opacity: 1; transform: scale(1) translateY(0); }
                }
            `}</style>
        </footer>
    );
}